[package]
name = "Reaxium"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdy-lib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Window"] }
